### ISSUE TITLE
NonText highlight group is reset when entering Ataraxis mode

### ISSUE THREAD

**Issue by noib3** [Pocco81/TrueZen.nvim#28]
This exact same [issue](https://github.com/junegunn/goyo.vim/issues/232) is also present in Goyo. Basically the value of the `NonText` highlight group set by the colorscheme is reset when entering Ataraxis mode.

Using the onedark colorscheme, the output of `:hi NonText`  before `:TZAtaraxis` is
```vim
:hi NonText
NonText        xxx ctermfg=238 guifg=#3B4048
```
and after
```vim
:hi NonText
NonText        xxx ctermfg=238 guifg=black
```

**Comment by Pocco81** [comment]
https://user-images.githubusercontent.com/58336662/120848407-5f257f00-c53a-11eb-9304-580edc26ff12.mp4

[You're](https://github.com/Pocco81/TrueZen.nvim#-notices) [welcome](https://github.com/Pocco81/TrueZen.nvim/commit/60308b48e684ff4ae39f1544a0c6fae90deb13a9) :)
