### ISSUE TITLE
TZFocus stay in the same line

### ISSUE THREAD

**Issue by romariorobby** [Pocco81/TrueZen.nvim#31]
I've noticed that when TZFocus activate the cursor line not in the same place, is there any option to change that behaviour ?

**Comment by Pocco81** [comment]
[You're welcome :)](https://github.com/Pocco81/TrueZen.nvim/commit/89226c6111ef624d2d3cf654ea8669c5e294ba2a)

**Comment by romariorobby** [comment]
This is awesome 👍 . Thanks.

**Comment by Pocco81** [comment]
No problem.
