### ISSUE TITLE
Possibility to make `ideal_writing_area_width` a range?

### ISSUE THREAD

**Issue by jrmallorca** [Pocco81/TrueZen.nvim#35]
Hello, I often switch my terminal between fullscreen mode and splitting with other applications on the screen. I have set my `ideal_writing_area_width` to 80 which is really nice when the terminal takes up only half the screen but insufficient (for me) when it's in fullscreen mode.

Would it be possible to have some kind of min/max `ideal_writing_area_width`? so when I turn off and on `TZAtaraxis` it will reset to a better size?

**Comment by Pocco81** [comment]
Hey!

> Would it be possible to have some kind of min/max ideal_writing_area_width?

I understand your idea but in that case, how would truezen know which width size to set? I think the best approach would be to, of course, have the range (min/max) but to choose the width based on the current UI's size within the range.

Would you like that?

**Comment by Pocco81** [comment]
This is the final implementation (excuse the video quality, github only allows 10mbs, so I has to improvise):

https://user-images.githubusercontent.com/58336662/125698718-95f577a5-f405-4032-ba8d-a73c7d14159e.mp4

As you can see you can set a min and a max for the `ideal_writing_area_width`. However, that's not all. You can also set a prefered size to be picked when possible. Like as in the video: "pick the max size when possible". Of course, you can still use the original ideal writing area mechanism by just passing one element to the table.

I'll release it as soon as the doc for it get updated.

**Comment by jrmallorca** [comment]
Wow that looks great! Thank you for implementing it. I was torn with using `just_do_it_for_me` or `ideal_writing_area_width` as the former would have a bit too much padding for me that I couldn't change at all and the latter providing a bit more customisability but only for one size. This should fix those problems!
