### ISSUE TITLE
`Vim(bufdo):E37: No write since last change (add ! to override)` when closing a mode.

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#43]
How to reproduce
---

 1. Open a file.
 2. Activate a TrueZen mode (with a `:TZ`... command).
 3. Change the file.
 4. Try to exit the TrueZen mode (with the same `:TZ`... command).

---

It seems like you are currently obligated to save your changes if you want to exit a mode. It would be nice if you could exit the modes without having to save your changes to the file. 

_Note: The changes would still appear in the original buffer after you close the mode, of course._

**Comment by Pocco81** [comment]
Hey! I wasn't able to reproduce the issue:

https://user-images.githubusercontent.com/58336662/126568154-b7aa8a19-5c1e-4b2f-86df-4aaabae712e7.mp4

Are you sure you are using the latest version of TrueZen? If so, could you provide a video or an image showing the error you get/why you are obligated to save the file before exiting a TrueZen mode?

**Comment by luiz00martins** [comment]
> why you are obligated to save the file before exiting a TrueZen mode.

Actually, my comment was (partially) wrong. I'm not obligated to save it, and the modified contents actually appear in the original buffer when exiting a mode, but I still get an error. What I meant by "obligated to save the file" is that, _to avoid the error_, I have to save the file before exiting the mode, otherwise it occurs. It does not appear if I save before exiting.

I think I have the current version, as I've just ran `:PlugUpdate`. About the configs, I copied the default configs, but got the same result. I also removed everything else from my `init.vim` while testing, and ran `:PlugClear` to rule out the possibility of conflicts with other plugins. Here's the whole `init.vim` for reference:
```.vim
call plug#begin(stdpath('data') . '/plugged')
	Plug 'Pocco81/TrueZen.nvim'
call plug#end()

lua << EOF
local true_zen = require("true-zen")

true_zen.setup({
	ui = {
		bottom = {
			laststatus = 0,
			ruler = false,
			showmode = false,
			showcmd = false,
			cmdheight = 1,
		},
		top = {
			showtabline = 0,
		},
		left = {
			number = false,
			relativenumber = false,
			signcolumn = "no",
		},
	},
	modes = {
		ataraxis = {
			left_padding = 32,
			right_padding = 32,
			top_padding = 1,
			bottom_padding = 1,
			ideal_writing_area_width = {0},
			just_do_it_for_me = true,
			keep_default_fold_fillchars = true,
			custome_bg = "",
			bg_configuration = true,
			quit = "untoggle",
			affected_higroups = {NonText = {}, FoldColumn = {}, ColorColumn = {}, VertSplit = {}, StatusLine = {}, StatusLineNC = {}, SignColumn = {}}
		},
		focus = {
			margin_of_error = 5,
			focus_method = "experimental"
		},
	},
	integrations = {
		vim_gitgutter = false,
		galaxyline = false,
		tmux = false,
		gitsigns = false,
		nvim_bufferline = false,
		limelight = false,
		vim_airline = false,
		vim_powerline = false,
		vim_signify = false,
		express_line = false,
		lualine = false,
	},
	misc = {
		on_off_commands = false,
		ui_elements_commands = false,
		cursor_by_mode = false,
	}
})
EOF
```

Images
---

Here I ran `:TZAtaraxis`, typed `abcde` and tried to exit with `:TZAtaraxis`:
![Screenshot from 2021-07-21 20-54-22](https://user-images.githubusercontent.com/43142209/126574762-04553872-eb19-4685-bb15-f519baf9de91.png)

It's also worth noting that, although it successfully exits Ataraxis, after this point, I cannot open it anymore. Running `:TZAtaraxis` doesn't open the mode and yields the same error, with the additional message "`Already only one window`":
![Screenshot from 2021-07-21 20-54-55](https://user-images.githubusercontent.com/43142209/126575011-999a2ea3-74da-4c13-a658-3df1104a4503.png)

**Comment by Pocco81** [comment]
In the end the issue was caused by the `hidden` setting not being set in your config, but don't worry about it now, truezen will now set it momentarily when needed. However, I'd you recommend you setting it because it's very useful for keeping and opening multiple buffers. :+1:
