### ISSUE TITLE
Maintaining cursor position when starting and exiting modes.

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#44]
Currently, starting Ataraxis mode results in the cursor starting at the first line and first column of the file. Leaving Ataraxis results in the cursor returning to the position it was in the original buffer when the mode was first opened.

It would be nice if the cursor by default (or as an option) would maintain its position while going in and out of modes. That is, if you were in the position `330,20`, starting Ataraxis would still leave you at `330,20`. And, if while editing in that mode you ended up in `510,18`, closing Ataraxis would drop you at `510,18`.

**Comment by Pocco81** [comment]
FYI this only happens on Ataraxis mode. I think someone pointed this same thing happening on focus mode and I fixed it. Anyways, I'll fix this too :)
