### ISSUE TITLE
[Feature Request] Padding delineation

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#45]
Currently, the buffer has the same color as the paddings around it, which makes it a bit hard to differentiate between what's buffer and what's left/right padding.
![Screenshot from 2021-07-23 16-56-38](https://user-images.githubusercontent.com/43142209/126842358-405982bd-c2cd-4370-85fe-bffe2f0e0b81.png)

I suggest an option to add some delineation to emphasize the buffer. 

One way I see is to add lines on the sides the buffer, VsCode Zen style (although I don't know how feasible this is in terminal):
![Screenshot from 2021-07-23 16-53-04](https://user-images.githubusercontent.com/43142209/126842619-dd1a3c6c-e863-4cc3-9902-5bf22b0d2074.png)

Another one, which I personally prefer, is to add a configurable darkening level, so the side paddings are slightly shaded, [zen-mode](https://github.com/folke/zen-mode.nvim) style:
![Screenshot from 2021-07-23 16-54-26](https://user-images.githubusercontent.com/43142209/126843989-f2c20bf5-9f3b-4de8-b77e-0b99690ffb29.png)

There may be more ways to implement this of course, these are just some examples of how it could be done.

**Comment by Pocco81** [comment]
Good idea! I implemented both padding delineation methods (darkening and putting a solid color). You can use the feat like so:

```lua
-- on truezen's conf
custom_bg = {"solid", "#1a1d1e"}, -- solid color
custom_bg = {"darken", 0.70}, -- darken by x degree
custom_bg = {"none", ""}, -- the one that was before

```

Here is a small sneak peek:

Solid:

![image](https://user-images.githubusercontent.com/58336662/126887278-f6863c8d-60c0-420a-bd77-c1583f1edfd2.png)

Darken:

![image](https://user-images.githubusercontent.com/58336662/126887288-c2902228-80b4-4800-9a8c-4bc5af78fc1f.png)

I also kept the one that was before btw:

![image](https://user-images.githubusercontent.com/58336662/126887304-a81257e4-730a-4498-a8a8-6b8ad9d13405.png)

The colors were, of course, for demonstration purposes haha.
