### ISSUE TITLE
Error `attempt to index a nil value` when `custom_bg` is set to `darken` but no background is set

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#46]
## How to reproduce ##
 
 1. Set TrueZen Ataraxis' `custom_bg` option to `darken` (e.g. `custom_bg = {"darken", 0.87}`)
 2. Start neovim without setting any background.
 3. Run `:TZArataxis`

----

Although it might not be possible, I suggest that TrueZen should fall back into darkening the terminal's background color. In case that's not viable, it would be nice to have a more graceful handling of the exception (e.g. issuing a warning when loading the setting, or ignoring the setting when there's no background, or showing an error message more informative than '`attempt to index a nil value`').

**Comment by Pocco81** [comment]
Hey! yep, forgot to add a fallback in case something like this occurred. I will fix this as soon as possible!

**Comment by Pocco81** [comment]
Okay so, I faced two problems. The first one was that I couldn't find a way to get the terminal color from vim and the second one was that you just **can't** deem a transparent background (in case the terminal was transparent). So the solution that I came up with was to determine whether it was `dark` or `light` the background and then based on that pick one of two colors (a dark blue if it was dark and a grey one if it was light).

I checked out how zenmode.nvim (originally mentioned in #45 as a reference) was implementing this, and well: 

![image](https://user-images.githubusercontent.com/58336662/127020332-ca473cb3-8dfa-4af7-81e1-e2eef2414e50.png)

It simply does nothing, which of course is a more graceful handling compared to what was before, however it defeats the purpose of the setting being used for darkening the background, plus you can already do that with `custom_bg = {"none", ""}`, at least of truezen.

But again, that's my opinion. Let me know which of two solutions solutions you liked the most! I'll merge this one with main and close the issue (after I update the doc).

**Comment by luiz00martins** [comment]
Hey @Pocco81! Took me a while to get check this out. I like your solution a little better, as it at least respects the setting in some sense, instead of ignoring it. 

One problem though: I was not able to replicate it, even with a non-transparent background. I've set both to `dark` and `light`, but it simply stuck with the default background:

With `background=dark`:
![Screenshot from 2021-08-06 05-33-08](https://user-images.githubusercontent.com/43142209/128482207-47e5a9cf-1673-44b1-9a64-d5a5f6ec4821.png)

With `background=light`:
![Screenshot from 2021-08-06 05-33-34](https://user-images.githubusercontent.com/43142209/128482255-bc9b7871-4bb6-4cdc-b20c-7c963e33ed4a.png)

**Comment by Pocco81** [comment]
1. Are you sure your background was transparent before? If not then `:hi Normal guibg=NONE ctermbg=NONE`
2. What did you have `custom_bg` set to? Remember that `custom_bg = {"none", ""}` does nothing and leaves you with the transparent background and `custom_bg = {"darken", <floating point number>}` will dim the background (regardless of you having a color or not).
3. May I see your TrueZen config?

Also, keep in mind that the `background` variable doesn't do much... I mean, TrueZen only uses it for picking a color for the background **in case you don't have one set**.

**Comment by luiz00martins** [comment]
My complete `init.vim` configs are present in the pictures, including the `custom_bg`. 

No, I have not set them to transparent, as the purpose was to test what happened when the background was _not_ transparent, but also wasn't set (i.e. it was using the default non-transparent background from the terminal). 

I expected it to either darken the default background, or, since I explicitly set `background` to `dark`/`light`, to use one of the two colors mentioned in your previous comment:

>So the solution that I came up with was to determine whether it was `dark` or `light` the background and then based on that pick one of two colors (a dark blue if it was dark and a grey one if it was light).

Was my expectation wrong?

**Comment by Pocco81** [comment]
> My complete init.vim configs are present in the pictures, including the custom_bg.

Do you mind using the default config in the README and replacing the `custom_bg` with the one you have in the pictures?

> No, I have not set them to transparent, as the purpose was to test what happened when the background was not transparent.

No, this issue requested a better way to handle when there was no background set. And no background set means that it's transparent. 

> default non-transparent background from the terminal.

There is no such thing like a "non-transparent background from the terminal". If it ain't transparent then it's using a default color set by nvim. Can I see the output of `:hi Normal`? :)

> I expected it to either darken the default background

If you are using a color for the background then it should've darken it. Not sure why it didn't. Could you set a background color yourself?

> Was my expectation wrong?

Yes, everything I'd mentioned before was for when there was **no background set**, and **no background** set means means that it's **transparent**.
