### ISSUE TITLE
Twilight.nvim integration

### ISSUE THREAD

**Issue by shaunsingh** [Pocco81/TrueZen.nvim#47]
Hello once again, loving the plugin. Is there any chance you could provide integration with https://github.com/folke/twilight.nvim? I would love it as a Lua-based alternative to the limelight plugin, which already has an integration. It would be as simple as running `:Twilight` on opening/closing truezen

**Comment by Pocco81** [comment]
Say no more!

**Comment by Pocco81** [comment]
Looks clean!

![image](https://user-images.githubusercontent.com/58336662/127224472-1485029a-580e-41d7-8801-67809aa85f27.png)

The feat was added! just add `twilight = true` to use it :+1:
