### ISSUE TITLE
`misc` section of configuration not working

### ISSUE THREAD

**Issue by jrmallorca** [Pocco81/TrueZen.nvim#49]
Hello, I've tried turning on `on_off_commands` and `ui_elements_commands` in the config but none of the commands appear (E.g. :TZAtaraxisOn, :TZBottomOn). `cursor_by_mode` has also stopped working but I don't know since when as I've only noticed it now.

Other areas work though. I can toggle options within the `ui` and `modes` sections.

I've also noticed that I can't access the general UI elements commands as well (E.g. :TZBottom), of which I don't know whether it's related to the above.

**Comment by Pocco81** [comment]
My bad! it should all be working now as expected :)
