### ISSUE TITLE
`:TZAtaraxisOff` quits neovim

### ISSUE THREAD

**Issue by jrmallorca** [Pocco81/TrueZen.nvim#50]
Hello, I don't know if this is intended but `:TZAtaraxisOff` quits neovim if TZAtaraxis mode isn't on.

Context for this issue: I want to create keybindings that easily switch between modes like these
```
vim.api.nvim_set_keymap('n', '<Leader>1', [[<Cmd>TZAtaraxisOff<CR><Cmd>TZMinimalistOff<CR><Cmd>TZFocusOff<CR><Cmd>TZAtaraxisOn<CR>]], { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<Leader>2', [[<Cmd>TZAtaraxisOff<CR><Cmd>TZMinimalistOff<CR><Cmd>TZFocusOff<CR><Cmd>TZMinimalistOn<CR>]], { noremap = true, silent = true })
```

**Comment by Pocco81** [comment]
From the README:

![image](https://user-images.githubusercontent.com/58336662/128435489-6d8d8b0f-f782-49f1-83b0-aa5aafd49269.png)

Perhaps you have it set to `"close"`? This is the default:

![image](https://user-images.githubusercontent.com/58336662/128435514-f6d22dcb-ebf0-4ffa-a906-e896fbfd9def.png)

**Comment by jrmallorca** [comment]
It still closes even if `quit` is equal to `"untoggle"` or `nil`.

**Comment by Pocco81** [comment]
Oh okay I saw the issue, let me fix it :)

**Comment by Pocco81** [comment]
Okay you should now be getting messages like this in case you can't do what you are trying to do instead of performing the action right away:

https://user-images.githubusercontent.com/58336662/128616093-d448011e-22cc-4572-928d-8564a1dbdbfd.mp4

**Comment by jrmallorca** [comment]
Yep my keybindings smoothly go through each mode now thank you!
