### ISSUE TITLE
Completely remove bottom/top paddings

### ISSUE THREAD

**Issue by luiz00martins** [Pocco81/TrueZen.nvim#51]
When setting `top_padding=0` and `bottom_padding=0`, there's still two lines of padding on the top and bottom. It'd be nice if those were completely removed when the paddings were set to 0.

Here's a picture of the current way it displays:
![Screenshot from 2021-08-06 06-35-10](https://user-images.githubusercontent.com/43142209/128490746-bf9f5164-a0bf-4a61-8a53-93a43fb3a4a5.png)

Here's a picture of how I wish it would displayed, for reference (using [zen-mode](https://github.com/folke/zen-mode.nvim)):
![Screenshot from 2021-08-06 06-34-55](https://user-images.githubusercontent.com/43142209/128490927-6062f321-2562-49eb-b6b9-04e3795be193.png)

_(don't mind the left and right paddings, the important difference is the bottom and top ones)_

**Comment by Pocco81** [comment]
Nice feature, I'll implement it. But just keep in mind that you can't remove the command section on nvim, so there will always be a one block tall space at the bottom:

![image](https://user-images.githubusercontent.com/58336662/128528609-f513f337-6ff9-44a0-90ef-8b90b5f2c7fd.png)

And as you can see zen mode also has it:

![image](https://user-images.githubusercontent.com/58336662/128528660-dbcf749f-5dce-42f7-99dc-16055a8d30c1.png)

**Comment by Pocco81** [comment]
You're welcome :)

**Comment by doongjohn** [comment]
is this change reverted after the rewrite?
