### ISSUE TITLE
Can't remove line numbers of nvim-toggleterm buffer

### ISSUE THREAD

**Issue by henriquehbr** [Pocco81/TrueZen.nvim#54]
When using `TrueZen.nvim` alongside [`nvim-toggleterm`](https://github.com/akinsho/nvim-toggleterm.lua), the ataraxis mode end up enforcing line numbers on the terminal buffer, example below:

![2021-08-12-121827_958x972_scrot](https://user-images.githubusercontent.com/31735860/129223208-ef1159bb-5b88-4a62-ac58-24ab3cb97d26.png)

Even though `nvim-toggleterm` documentation specify a `hide_numbers` property, setting it to `true` doesn't works, any clue of what might be happening?

> Note: this problem started showing up after i began using `TrueZen`, when `nvim-toggleterm` was already installed

**Comment by Pocco81** [comment]
Fixed! Should be working now :)

**Comment by henriquehbr** [comment]
Working flawlessly! thanks again :)
