### ISSUE TITLE
lightline.vim integration

### ISSUE THREAD

**Issue by dm9pZCAq** [Pocco81/TrueZen.nvim#56]
> If it fails, then open an issue and request for the integration

it will be great to have integration with [itchyny/lightline.vim](https://github.com/itchyny/lightline.vim) 

when i enables `TZAtaraxis` then statusbar appears on top:

![default](https://0x0.st/-yz5.png)
![TZAtaraxis](https://0x0.st/-yzn.png)

related issue: itchyny/lightline.vim/issues/588

**Comment by dm9pZCAq** [comment]
as i see `TrueZen` creates new split and resize previous split to 0

and in new split sets `laststatus` to `0`, but in previous split status still shown

and when i moving through splits with `<C-w>j` `<C-w>k` statusline appears on all splits 

![<C-w>k](https://0x0.st/-yiO.png)

**Comment by Pocco81** [comment]
You're welcome :) Btw, unrelated to the issue itself, but thanks to this I ended up improving the handling of unsupported statuslines by TrueZen :+1:

**Comment by dm9pZCAq** [comment]
hello @Pocco81 
why are you removed this integration?
