### ISSUE TITLE
Integrations not working and odd top bar

### ISSUE THREAD

**Issue by d-miketa** [Pocco81/TrueZen.nvim#57]
Hi, thanks for the wonderful plugin! I'm only facing two difficulties:

First, some integrations aren't working in Ataraxis mode.
```
use {
    'Pocco81/TrueZen.nvim',
    requires = {{'folke/twilight.nvim', opt = true}, {'lewis6991/gitsigns.nvim', opt = true}},
    config = function()
        require'true-zen'.setup {
            integrations = {
                gitsigns = true,
                twilight = true
            }
        }
    end
      }
```
`twilight` is doing fine but the `gitsigns` option is completely inert.

Second, the Ataraxis mode has an odd bar at the top.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/320321/130091230-a0be3483-4ade-4b51-b8c6-228bdd9ab3f0.png">

What can I do to help diagnose the issues?

**Comment by Pocco81** [comment]
Which statusline are you using?

**Comment by d-miketa** [comment]
I'm using Lualine. Incidentally, the `lualine` option isn't doing anything for me either.

**Comment by Pocco81** [comment]
> `gitsigns` option is completely inert.

That's what it's supposed to do. From the README:

![image](https://user-images.githubusercontent.com/58336662/130111380-ddeb489d-42e1-4ba9-b9cd-5fa56e7cb75e.png)

TrueZen's goal is to provide a cleaner interface without all the clutter, and if you've used gitsigns in the past then you already know all the things it puts on the screen (mainly virtual text and huge highlights). That's why this integration does that. If you want gitsigns while on Ataraxis mode then simply don't enable the integration and use gitsigns as usual.

> lualine option isn't doing anything for me either.

Yeah there was a small type in the code, my bad! :)

> Thanks for the wonderful plugin!

Thank for using it :]

**Comment by d-miketa** [comment]
Thanks for fixing the Lualine integration!

I understand how `gitsigns` works. The problem's that setting it to `true` or `false` makes no difference to my config, there are no gitsigns visible.

**Comment by Pocco81** [comment]
Oh no no I think you are getting the wrong idea. Setting any integration to `false` ≠ doing the opposite of what the integration is meant to do. It simply does nothing.

With that said, setting the git signs integration to `true` will disable git sings while on Ataraxis mode, while setting it to `false` will simply not interact with gitsigns. What I mean is, if you don't see git sings outside of any TrueZen stuff then it's in your nvim config, just enable it at startup or something.

**Comment by d-miketa** [comment]
With Ataraxis:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/320321/130147871-9596d214-2968-4517-ae4b-61dced621f56.png">

Without Ataraxis:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/320321/130147900-818fc4a3-a6db-4a57-889b-469e3d1f7b45.png">

That said, I am having some independent issues with gitsigns (not loading until a bit into the session, on specific triggers etc), so maybe there's something wrong with my config.

**Comment by Pocco81** [comment]
> independent issues with gitsigns

well then if you have issues with that plugin consider opening an issue in their repo :)

Also, is not like gitsigns is something you can see right away if you don't have anything to be preloaded at startup. 

https://user-images.githubusercontent.com/58336662/130158289-9b9c9e4e-c1bc-45ca-b0bf-037723444e53.mp4

You should try reading its doc :+1:

**Comment by d-miketa** [comment]
Appreciate the video, and I have already opened a bug report with Gitsigns over the issues I mentioned.

I'm starting to understand the confusion here. I assumed Ataraxis would show the colourful gutter lines indicating which hunks have been modified – unless `gitsigns = true`. But perhaps the intention is to _always_ hide the gutter lines in Ataraxis and let `gitsigns = true/false` control appearance only of in-text messages such as git blame? That seems to be working well. :)

Thanks for the patience, and a lovely plugin!
