### ISSUE TITLE
Inactive statusline displayed above the file in Ataraxis mode

### ISSUE THREAD

**Issue by d-miketa** [Pocco81/TrueZen.nvim#60]
Hi, thanks for this plugin and a phenomenal dotfiles repo! It's been very helpful, as you'll be able to see in the screenshot below:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/320321/132143779-61ec8735-d8d0-4bbe-ac00-349e4fc767ae.png">

You're looking at Ataraxis mode switched on with Feline and bufferline, the latter's integration turned on. There's a window right above the bit with code and it has an 'inactive' statusbar (in Feline). Have you run across this?

**Comment by Pocco81** [comment]
Hello :) Glad you liked my dots and this plugin!

>  Have you run across this?

Nope, and it's really weird that this is occurring since we both are using the same statusline... I moved to Feline like 2 days ago, and it works flawlessly with TrueZen.

+ Can I see your TrueZen conf?
+ Your nvim dots?
+ Feline conf?

**Comment by d-miketa** [comment]
Sure, thanks for taking the time!

<script src="https://gist.github.com/d-miketa/f15e3b175232e719945f19c1206642ad.js"></script>

It's not the whole thing, but as far as I can tell it's all the relevant bits.

**Comment by Pocco81** [comment]
First off, sorry for taking so long to get back to you. With that said, I couldn't reproduce the issue:

![image](https://user-images.githubusercontent.com/58336662/132440270-92602a57-9585-46d1-8ec4-50d75c41c638.png)

Can I see your whole TrueZen conf? Right now my best guess is that this is something related to a hi group (which were refactored [recently](https://github.com/Pocco81/TrueZen.nvim/commit/049b1578898b1949963dad08c91c26aab045aebe)). and btw, could you elaborate on the steps to reproduce the issue? Do you have TrueZen setup to open at startup or something similar?

**Comment by d-miketa** [comment]
The (very minimal) TrueZen config is towards the end of the Gist I posted. I use `:TZAtaraxis` to fire it up. And I don't think it's hl groups, which I tried playing with a little bit. I did notice that your personal Feline doesn't have any inactive components (which is what's showing up in my screenshot). Did you test with mine?

**Comment by Pocco81** [comment]
Ooh okay it was probably that, I didn't copy your feline config but the rest. I'll try your feline conf ASAP.

**Comment by Pocco81** [comment]
#60 resolves this. Enjoy the feline.nvim integration!
