### ISSUE TITLE
Character over ColorColumn gets hidden with TZAtaraxis

### ISSUE THREAD

**Issue by Groctel** [Pocco81/TrueZen.nvim#61]
Hi!

I've found that using `TZAtaraxis` with `colorcolumn` hides the character over that column no mater. Here are my settings:

```lua
require('true-zen').setup({
	integrations = {galaxyline = true},
	modes = { ataraxis = {
		affected_higroups = {ColorColumn = {}}
	}}
})
```

It gets hidden also when `ColorColumn = {'ignore'}`. Here's a visual example of the problem:

**Normal mode:**
![image](https://user-images.githubusercontent.com/32376781/132204931-0dcebef7-5293-4777-b728-077c38c6abab.png)

**Ataraxis mode:**
![image](https://user-images.githubusercontent.com/32376781/132204990-d2e4ffbe-1cb7-4610-ba2b-676bbc39f2c3.png)

Thanks for the amazing plugin!

**Comment by Pocco81** [comment]
See what I commented under #62 :)

**Comment by Pocco81** [comment]
Now you should be able to:
```lua
affected_higroups = {ColorColumn = false}
```

to stop TrueZen from overriding certain highlight groups.
