### ISSUE TITLE
Inactive status bar appearing in top padding in Atraxis Mode with Lualine

### ISSUE THREAD

**Issue by SoftAnnaLee** [Pocco81/TrueZen.nvim#73]
Hi I just installed this plugin and it works great, however I noticed an issue where an inactive status bar will appear in the top padding in Atraxis mode. 

![image](https://user-images.githubusercontent.com/40257903/146590111-db0f84f3-c6bf-41fc-832f-5acd2229dcbc.png)

I noticed #60 had reported the same issue, however that issue involved Feline. Meanwhile I use lualine but the same issue is appearing for me. Let me know if you need my configurations at all.

**Comment by Pocco81** [comment]
> Let me know if you need my configurations at all.

Yep for sure, I'd like to see them; both your lualine and TrueZen confs.

**Comment by SoftAnnaLee** [comment]
Sorry, I had realized I accidentally unset lualine integration while configuring this plugin. Fixed it and now it works wonderfully. Sorry about that. :sweat_smile:

**Comment by Pocco81** [comment]
Hahah no problem!
